language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - if test `uname -s` = 'Linux' then; sudo apt-get install autopoint; fi
install:
  - ./synclibs.sh && ./autogen.sh
script:
  - ./configure && make && make check
