language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - test `uname -s` = 'Linux' && sudo apt-get install autopoint
install:
  - ./synclibs.sh && ./autogen.sh
script:
  - ./configure && make && make check
