environment:
  VisualStudioVersion: 11.0

platform:
  - x86
  - x64

configuration:
  - Release
  - VSDebug

install:
  - cmd: git clone https://github.com/libyal/libyal

before_build:
  - cmd: git clone https://github.com/libyal/libcstring libcstring.git
  - cmd: move libcstring.git\libcstring .
  - cmd: rmdir /q /s libcstring.git
  - cmd: C:\Python27\python.exe libyal\msvscpp-convert.py --to 2010 msvscpp\libcerror.sln

build:
  project: vs2010\libcerror.sln

