environment:
  - VisualStudioVersion: 10.0

platform:
  - x86
  - x64

configuration:
  - Release
  - VSDebug

install:
  - cmd: git clone https://github.com/libyal/libyal

before_build:
  - cmd: git clone https://github.com/libyal/libcstring libcstring.tmp
  - cmd: move libcstring\libcstring .
  - cmd: rmdir /s libcstring.tmp
  - cmd: C:\Python27\python.exe libyal\msvscpp-convert.py --to vs2010

build:
  project: vs2010\libcerror.sln

